# Generated by Django 5.2.8 on 2025-11-16 23:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números e hífens (sem espaços).', regex='^[a-z0-9-]+$')], verbose_name='Domínio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('valid_until', models.DateField(blank=True, help_text='Data de validade do contrato.', null=True, verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Contrato Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Painel')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
