# Generated by Django 5.2.8 on 2025-11-16 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Enterprise')),
                ('document', models.CharField(blank=True, max_length=18, null=True, verbose_name='Documento (CNPJ ou CPF)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Enterprise')),
                ('address_street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rua')),
                ('address_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('address_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='management.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
                'ordering': ['name'],
            },
        ),
    ]
