# Generated by Django 5.2.8 on 2025-11-18 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('partner', 'Partner'), ('admin', 'Admin'), ('employee', 'Employee'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('invite_status', models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_sent', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.enterprise', verbose_name='Enterprise')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
    ]
