# Generated by Django 5.2.8 on 2025-11-18 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('enterprise', 'email'), name='unique_member_per_enterprise_email'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('enterprise', 'cpf'), name='unique_member_per_enterprise_cpf'),
        ),
    ]
