# Generated by Django 5.2.8 on 2025-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_member_options_alter_member_enterprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
