# Generated by Django 5.2.8 on 2025-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_enterprise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
    ]
