# Generated by Django 5.2.8 on 2025-11-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_tolerance', models.PositiveIntegerField(default=0, help_text='Permite aceitar agendamentos que invadam até essa quantidade de minutos do próximo horário disponível.', verbose_name='Tolerância de Sobreposição (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_config', to='organization.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuração de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamentos',
            },
        ),
    ]
