# Generated by Django 5.2.8 on 2025-11-11 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': 'Tipos de Atendimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('appointments', models.ManyToManyField(blank=True, related_name='workers', to='schedule.appointment', verbose_name='Atendimentos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Painel')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('monday', models.JSONField(blank=True, default=list, null=True, verbose_name='Monday')),
                ('tuesday', models.JSONField(blank=True, default=list, null=True, verbose_name='Tuesday')),
                ('wednesday', models.JSONField(blank=True, default=list, null=True, verbose_name='Wednesday')),
                ('thursday', models.JSONField(blank=True, default=list, null=True, verbose_name='Thursday')),
                ('friday', models.JSONField(blank=True, default=list, null=True, verbose_name='Friday')),
                ('saturday', models.JSONField(blank=True, default=list, null=True, verbose_name='Saturday')),
                ('sunday', models.JSONField(blank=True, default=list, null=True, verbose_name='Sunday')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='schedule.worker', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Worker Availability',
                'verbose_name_plural': 'Worker Availabilities',
                'db_table': 'worker_availability',
            },
        ),
    ]
