# Generated by Django 5.2.8 on 2025-11-10 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Lista de Atendimentos',
                'ordering': ['name'],
            },
        ),
    ]
