# Generated by Django 5.2.8 on 2025-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Tempo estimado do atendimento, em minutos (ex: 30, 45, 60)', verbose_name='Duração (minutos)'),
        ),
    ]
