# Generated by Django 5.2.8 on 2025-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers', to='schedule.appointment', verbose_name='Atendimentos'),
        ),
    ]
