# Generated by Django 5.2.8 on 2025-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_enterprise_options'),
        ('schedule', '0002_alter_worker_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('enterprise', 'name')},
        ),
    ]
