# Generated by Django 5.2.8 on 2025-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_schedulingconfig'),
        ('schedule', '0003_alter_appointment_name_alter_appointment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='workers', to='schedule.appointment', verbose_name='Atendimentos'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='friday',
            field=models.JSONField(blank=True, default=list, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='monday',
            field=models.JSONField(blank=True, default=list, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='saturday',
            field=models.JSONField(blank=True, default=list, verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='sunday',
            field=models.JSONField(blank=True, default=list, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='thursday',
            field=models.JSONField(blank=True, default=list, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='tuesday',
            field=models.JSONField(blank=True, default=list, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='workeravailability',
            name='wednesday',
            field=models.JSONField(blank=True, default=list, verbose_name='Wednesday'),
        ),
        migrations.AddConstraint(
            model_name='workeravailability',
            constraint=models.UniqueConstraint(fields=('worker',), name='unique_worker_availability'),
        ),
    ]
