# Generated by Django 5.2.8 on 2025-11-22 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('organization', '0008_schedulingconfig'),
        ('schedule', '0004_alter_worker_appointments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('duration', models.PositiveIntegerField(default=0, editable=False, verbose_name='Duração Total (min)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('appointments', models.ManyToManyField(related_name='bookings', to='schedule.appointment', verbose_name='Tipos de Atendimento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='clientes.client', verbose_name='Cliente')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='organization.enterprise', verbose_name='Empresa')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.worker', verbose_name='Profissional / Agenda')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
