# Generated by Django 5.2.8 on 2025-11-22 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_schedulingconfig'),
        ('schedule', '0005_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Duração Total (min)'),
        ),
        migrations.CreateModel(
            name='SchedulingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_windows', to='organization.enterprise')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_windows', to='schedule.worker')),
            ],
            options={
                'verbose_name': 'Scheduling Window',
                'verbose_name_plural': 'Scheduling Windows',
                'ordering': ('date',),
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingWindowInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(editable=False)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='schedule.schedulingwindow')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
