# Generated by Django 5.2.8 on 2025-11-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_scheduling_duration_schedulingwindow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingwindowinterval',
            name='window',
        ),
        migrations.DeleteModel(
            name='SchedulingWindow',
        ),
        migrations.DeleteModel(
            name='SchedulingWindowInterval',
        ),
    ]
