# Usa imagem leve do Python 3.12
FROM python:3.12-slim

# Evita criação de arquivos .pyc e força logs diretos
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Define diretório de trabalho
WORKDIR /home/user/app

# Instala dependências do sistema necessárias para builds de libs Python
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    libpq-dev \
    libssl-dev \
    zlib1g-dev \
    libjpeg-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Instala o pipenv
RUN pip install --no-cache-dir pipenv

# Copia o código do projeto
COPY ../ .

RUN pipenv install django

# Mantém o container em pé
CMD ["tail", "-f", "/dev/null"]
