FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TZ=America/Sao_Paulo

WORKDIR /home/user/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    curl \
    build-essential \
    libpq-dev \
    libssl-dev \
    zlib1g-dev \
    libjpeg-dev \
    git \
    && ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime \
    && echo "America/Sao_Paulo" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pipenv

COPY ../ .

RUN pipenv install django

CMD ["tail", "-f", "/dev/null"]
