# Generated by Django 5.2.8 on 2025-11-21 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_schedulingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('address_street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rua')),
                ('address_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('address_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organization.enterprise', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('enterprise', 'email'), name='unique_client_email_per_enterprise'), models.UniqueConstraint(fields=('enterprise', 'cpf'), name='unique_client_cpf_per_enterprise')],
            },
        ),
    ]
