# Generated by Django 5.2.8 on 2025-11-16 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productEnterprise', to='organization.enterprise', verbose_name='Enterprise')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
