# Generated by Django 5.2.8 on 2025-11-10 16:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço (R$)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_text',
            field=models.CharField(blank=True, help_text='Campo exibido apenas para entrada formatada (ex: R$ 1.234,56)', max_length=50, verbose_name='Preço (texto)'),
        ),
    ]
