# Generated by Django 5.2.8 on 2025-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_text',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, null=True, verbose_name='Preço (R$)'),
        ),
    ]
